[project]
name = "fll2025-unearthed-team-bx4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "black>=25.1.0",
    "pybricks>=3.6.1",
    "pybricksdev>=1.2.0",
]
